### PR TITLE
Send empty body on PUT so curl sends content-length header

### PR DESCRIPTION
**Pull request by vincent99**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
WTH???

**Comment by ibuildthecloud** [comment]
This would need to change also: https://github.com/rancher/cattle/blob/master/resources/content/config-content/configscripts/common/scripts.sh#L58

I don't understand how you'd get to the point that rancher-net doesn't work if the same logic in cattle fails.

**Comment by vincent99** [comment]
The Azure load balancer appears to return 411 if a PUT is sent with no body and no content length.  -d "" causes it to send 0.  I didn't test it, it's possible the other place is needed too but this is where it was failing for @flaccid.

**Comment by flaccid** [comment]
Azure RM Application Load Balancer, he is a special guy.

**Pull request merged**
