### PR TITLE
Cleanup packaging Dockerfile

### PR DESCRIPTION
**Pull request by cjellick**
No functional changes, just make it more readable and remove redundant
code. I believe it got to this point from a series a small changes that
didn't look at the bigger picture.

### CODE REVIEW

**Comment by cjellick** [comment]
@ibuildthecloud @leodotcloud The fact that we have to rename rancher-cni-bridge to rancher-bridge is kind of dumb. As a separate change, how would you feel about me changing the binary created in the rancher-cni-bridge project to just be rancher-bridge?

**Comment by leodotcloud** [comment]
@cjellick It makes sense to keep "rancher-cni-bridge" as the binary name, I would prefer that over "rancher-bridge". But that would need a change in the rancher-catalog.

**Comment by leodotcloud** [comment]
Otherwise, the changes seem reasonable and good. Once you test and have it working, LGTM.

**Comment by cjellick** [comment]
@leodotcloud do you know why we rename the binary to rancher-bridge in the first place?

**Comment by leodotcloud** [comment]
@cjellick I think we just wanted to change the name from the default CNI plugin name "bridge" to "rancher-bridge" so that it shows up like that in the CNI config of our IPSec/VXLAN plugins.

See: https://github.com/rancher/rancher-catalog/blob/master/infra-templates/ipsec/3/rancher-compose.yml#L46

**Comment by leodotcloud** [comment]
@cjellick I think I had made changes when I switched from the upstream plugin to our own, but somehow I missed to get those changes in the earlier PR.

It definitely makes sense to rename, now that I am looking at this line: https://github.com/rancher/rancher-catalog/blob/master/infra-templates/ipsec/3/rancher-compose.yml#L57

**Comment by cjellick** [comment]
cool! let's do it. we can do it in phases. I'll leave this PR as-is and test it and confirm it works.
then we can merge this one and in another PR drop the renaming to rancher-bridge and coordiante that with a catalog change

**Comment by cjellick** [comment]
@leodotcloud i tested/confirmed it works

**Comment by leodotcloud** [comment]
LGTM

**Pull request merged**
