### PR TITLE
Let vtep interface MTU to be configurable

### PR DESCRIPTION
**Pull request by niusmallnan**
https://github.com/rancher/rancher/issues/8411

### CODE REVIEW

**Comment by leodotcloud** [comment]
LGTM

**Comment by leodotcloud** [comment]
@niusmallnan can you please make a PR for `rancher-catalog`?

**Comment by niusmallnan** [comment]
@leodotcloud  which tag? v0.11.9?

**Comment by leodotcloud** [comment]
@niusmallnan Yes v0.11.9. Could you also take care of passing the catalog answer variable to the vtep environment variable?

**Pull request merged**
